"""Initial schema

Revision ID: f4dc3e28448d
Revises: a7018127b83e
Create Date: 2025-12-16 18:11:49.469291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = 'f4dc3e28448d'
down_revision = 'a7018127b83e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hardcover_sync_logs_abs_item_id'), table_name='hardcover_sync_logs')
    op.drop_index(op.f('ix_hardcover_sync_logs_id'), table_name='hardcover_sync_logs')
    op.drop_index(op.f('ix_hardcover_sync_logs_synced_at'), table_name='hardcover_sync_logs')
    op.drop_table('hardcover_sync_logs')
    op.drop_index(op.f('ix_event_status_active'), table_name='event_status')
    op.drop_index(op.f('ix_event_status_event_type'), table_name='event_status')
    op.drop_index(op.f('ix_event_status_id'), table_name='event_status')
    op.drop_table('event_status')
    op.drop_index(op.f('ix_rule_cache_category_name'), table_name='rule_cache')
    op.drop_index(op.f('ix_rule_cache_id'), table_name='rule_cache')
    op.drop_index(op.f('ix_rule_cache_last_checked'), table_name='rule_cache')
    op.drop_table('rule_cache')
    op.drop_index(op.f('ix_evidence_sources_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_name'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_ratio_log_emergency_active'), table_name='ratio_log')
    op.drop_index(op.f('ix_ratio_log_global_ratio'), table_name='ratio_log')
    op.drop_index(op.f('ix_ratio_log_id'), table_name='ratio_log')
    op.drop_index(op.f('ix_ratio_log_timestamp'), table_name='ratio_log')
    op.drop_table('ratio_log')
    op.drop_index(op.f('ix_mam_rules_effective_date'), table_name='mam_rules')
    op.drop_index(op.f('ix_mam_rules_rule_version'), table_name='mam_rules')
    op.drop_table('mam_rules')
    op.drop_index(op.f('ix_missing_books_author_id'), table_name='missing_books')
    op.drop_index(op.f('ix_missing_books_download_status'), table_name='missing_books')
    op.drop_index(op.f('ix_missing_books_id'), table_name='missing_books')
    op.drop_index(op.f('ix_missing_books_identified_date'), table_name='missing_books')
    op.drop_index(op.f('ix_missing_books_series_id'), table_name='missing_books')
    op.drop_table('missing_books')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_abs_id'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_index(op.f('ix_books_date_added'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_series'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_goodreads_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_last_completion_check'), table_name='authors')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_series_completion_status'), table_name='series')
    op.drop_index(op.f('ix_series_goodreads_id'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_index(op.f('ix_series_name'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_failed_attempts_attempt_count'), table_name='failed_attempts')
    op.drop_index(op.f('ix_failed_attempts_created_at'), table_name='failed_attempts')
    op.drop_index(op.f('ix_failed_attempts_id'), table_name='failed_attempts')
    op.drop_index(op.f('ix_failed_attempts_item_id'), table_name='failed_attempts')
    op.drop_index(op.f('ix_failed_attempts_last_attempt'), table_name='failed_attempts')
    op.drop_index(op.f('ix_failed_attempts_task_name'), table_name='failed_attempts')
    op.drop_table('failed_attempts')
    op.drop_index(op.f('ix_assertions_book_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_evidence_event_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_field'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_is_human_override'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_source_id'), table_name='assertions')
    op.drop_index(op.f('ix_assertions_value_fingerprint'), table_name='assertions')
    op.drop_table('assertions')
    op.drop_index(op.f('ix_metadata_corrections_book_id'), table_name='metadata_corrections')
    op.drop_index(op.f('ix_metadata_corrections_correction_date'), table_name='metadata_corrections')
    op.drop_index(op.f('ix_metadata_corrections_field_name'), table_name='metadata_corrections')
    op.drop_index(op.f('ix_metadata_corrections_id'), table_name='metadata_corrections')
    op.drop_index(op.f('ix_metadata_corrections_source'), table_name='metadata_corrections')
    op.drop_table('metadata_corrections')
    op.drop_index(op.f('idx_emergency_timestamp'), table_name='ratio_metrics')
    op.drop_index(op.f('idx_timestamp_desc'), table_name='ratio_metrics')
    op.drop_index(op.f('ix_ratio_metrics_id'), table_name='ratio_metrics')
    op.drop_index(op.f('ix_ratio_metrics_timestamp'), table_name='ratio_metrics')
    op.drop_table('ratio_metrics')
    op.drop_index(op.f('ix_downloads_book_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_date_queued'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_next_retry'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_qbittorrent_hash'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_source'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_status'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_tasks_date_created'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduled_time'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_name'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('ix_evidence_events_book_id'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_id'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_request_fingerprint'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_source_id'), table_name='evidence_events')
    op.drop_table('evidence_events')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_status_auto_download'), table_name='vip_pending_items')
    op.drop_index(op.f('ix_vip_pending_items_added_date'), table_name='vip_pending_items')
    op.drop_index(op.f('ix_vip_pending_items_id'), table_name='vip_pending_items')
    op.drop_index(op.f('ix_vip_pending_items_mam_torrent_id'), table_name='vip_pending_items')
    op.drop_index(op.f('ix_vip_pending_items_status'), table_name='vip_pending_items')
    op.drop_table('vip_pending_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_pending_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('mam_torrent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auto_download', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reason_pending', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vip_pending_items_pkey'))
    )
    op.create_index(op.f('ix_vip_pending_items_status'), 'vip_pending_items', ['status'], unique=False)
    op.create_index(op.f('ix_vip_pending_items_mam_torrent_id'), 'vip_pending_items', ['mam_torrent_id'], unique=False)
    op.create_index(op.f('ix_vip_pending_items_id'), 'vip_pending_items', ['id'], unique=False)
    op.create_index(op.f('ix_vip_pending_items_added_date'), 'vip_pending_items', ['added_date'], unique=False)
    op.create_index(op.f('idx_status_auto_download'), 'vip_pending_items', ['status', 'auto_download'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('evidence_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('evidence_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='evidence_events_book_id_fkey'),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], name='evidence_events_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evidence_events_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_evidence_events_source_id'), 'evidence_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_events_request_fingerprint'), 'evidence_events', ['request_fingerprint'], unique=False)
    op.create_index(op.f('ix_evidence_events_id'), 'evidence_events', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_events_book_id'), 'evidence_events', ['book_id'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('items_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_succeeded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vip_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vip_expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('renewal_decision', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('point_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('renewal_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rules_updated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pending_items_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('emergency_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_scheduled_time'), 'tasks', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_date_created'), 'tasks', ['date_created'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('downloads_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('magnet_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('torrent_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qbittorrent_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('qbittorrent_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_retry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('abs_import_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('abs_import_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_queued', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('integrity_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('release_edition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emergency_blocked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_download_allowed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('freeze_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('emergency_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='downloads_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['missing_book_id'], ['missing_books.id'], name='downloads_missing_book_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='downloads_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_downloads_status'), 'downloads', ['status'], unique=False)
    op.create_index(op.f('ix_downloads_source'), 'downloads', ['source'], unique=False)
    op.create_index(op.f('ix_downloads_qbittorrent_hash'), 'downloads', ['qbittorrent_hash'], unique=False)
    op.create_index(op.f('ix_downloads_next_retry'), 'downloads', ['next_retry'], unique=False)
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_index(op.f('ix_downloads_date_queued'), 'downloads', ['date_queued'], unique=False)
    op.create_index(op.f('ix_downloads_book_id'), 'downloads', ['book_id'], unique=False)
    op.create_table('ratio_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('global_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('upload_rate_mbps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('download_rate_mbps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('active_uploads', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active_downloads', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points_earned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points_spent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emergency_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ratio_metrics_pkey'))
    )
    op.create_index(op.f('ix_ratio_metrics_timestamp'), 'ratio_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ratio_metrics_id'), 'ratio_metrics', ['id'], unique=False)
    op.create_index(op.f('idx_timestamp_desc'), 'ratio_metrics', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_emergency_timestamp'), 'ratio_metrics', ['emergency_active', 'timestamp'], unique=False)
    op.create_table('metadata_corrections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('correction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('corrected_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('metadata_corrections_book_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('metadata_corrections_pkey'))
    )
    op.create_index(op.f('ix_metadata_corrections_source'), 'metadata_corrections', ['source'], unique=False)
    op.create_index(op.f('ix_metadata_corrections_id'), 'metadata_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_corrections_field_name'), 'metadata_corrections', ['field_name'], unique=False)
    op.create_index(op.f('ix_metadata_corrections_correction_date'), 'metadata_corrections', ['correction_date'], unique=False)
    op.create_index(op.f('ix_metadata_corrections_book_id'), 'metadata_corrections', ['book_id'], unique=False)
    op.create_table('assertions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evidence_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('value_fingerprint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resolution_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('method_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_modifier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_human_override', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('assertions_book_id_fkey')),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['evidence_events.id'], name=op.f('assertions_evidence_event_id_fkey')),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], name=op.f('assertions_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assertions_pkey'))
    )
    op.create_index(op.f('ix_assertions_value_fingerprint'), 'assertions', ['value_fingerprint'], unique=False)
    op.create_index(op.f('ix_assertions_source_id'), 'assertions', ['source_id'], unique=False)
    op.create_index(op.f('ix_assertions_is_human_override'), 'assertions', ['is_human_override'], unique=False)
    op.create_index(op.f('ix_assertions_id'), 'assertions', ['id'], unique=False)
    op.create_index(op.f('ix_assertions_field'), 'assertions', ['field'], unique=False)
    op.create_index(op.f('ix_assertions_evidence_event_id'), 'assertions', ['evidence_event_id'], unique=False)
    op.create_index(op.f('ix_assertions_book_id'), 'assertions', ['book_id'], unique=False)
    op.create_table('failed_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempt_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('failed_attempts_pkey'))
    )
    op.create_index(op.f('ix_failed_attempts_task_name'), 'failed_attempts', ['task_name'], unique=False)
    op.create_index(op.f('ix_failed_attempts_last_attempt'), 'failed_attempts', ['last_attempt'], unique=False)
    op.create_index(op.f('ix_failed_attempts_item_id'), 'failed_attempts', ['item_id'], unique=False)
    op.create_index(op.f('ix_failed_attempts_id'), 'failed_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_failed_attempts_created_at'), 'failed_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_failed_attempts_attempt_count'), 'failed_attempts', ['attempt_count'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('series_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('goodreads_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_books_in_series', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('books_owned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('books_missing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_completion_check', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completion_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='series_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_series_name'), 'series', ['name'], unique=True)
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_goodreads_id'), 'series', ['goodreads_id'], unique=False)
    op.create_index(op.f('ix_series_completion_status'), 'series', ['completion_status'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('authors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('goodreads_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('google_books_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mam_author_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_audiobooks_external', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audiobooks_owned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audiobooks_missing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_completion_check', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completion_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='authors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=True)
    op.create_index(op.f('ix_authors_last_completion_check'), 'authors', ['last_completion_check'], unique=False)
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_goodreads_id'), 'authors', ['goodreads_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('books_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('abs_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('series', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('series_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('asin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('published_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_completeness_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_metadata_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata_source', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('import_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('narrator', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mam_rule_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duplicate_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_series'), 'books', ['series'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_date_added'), 'books', ['date_added'], unique=False)
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_abs_id'), 'books', ['abs_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('login_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('missing_books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('series_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('series_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reason_missing', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('asin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('goodreads_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('identified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('download_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('download_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('missing_books_author_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('missing_books_book_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['download_id'], ['downloads.id'], name=op.f('missing_books_download_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('missing_books_series_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('missing_books_pkey'))
    )
    op.create_index(op.f('ix_missing_books_series_id'), 'missing_books', ['series_id'], unique=False)
    op.create_index(op.f('ix_missing_books_identified_date'), 'missing_books', ['identified_date'], unique=False)
    op.create_index(op.f('ix_missing_books_id'), 'missing_books', ['id'], unique=False)
    op.create_index(op.f('ix_missing_books_download_status'), 'missing_books', ['download_status'], unique=False)
    op.create_index(op.f('ix_missing_books_author_id'), 'missing_books', ['author_id'], unique=False)
    op.create_table('mam_rules',
    sa.Column('rule_version', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('effective_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rules_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('freeleech_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bonus_event_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('multiplier_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('event_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rule_version', name=op.f('mam_rules_pkey'))
    )
    op.create_index(op.f('ix_mam_rules_rule_version'), 'mam_rules', ['rule_version'], unique=False)
    op.create_index(op.f('ix_mam_rules_effective_date'), 'mam_rules', ['effective_date'], unique=False)
    op.create_table('ratio_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('global_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('emergency_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('seeding_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ratio_log_pkey'))
    )
    op.create_index(op.f('ix_ratio_log_timestamp'), 'ratio_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ratio_log_id'), 'ratio_log', ['id'], unique=False)
    op.create_index(op.f('ix_ratio_log_global_ratio'), 'ratio_log', ['global_ratio'], unique=False)
    op.create_index(op.f('ix_ratio_log_emergency_active'), 'ratio_log', ['emergency_active'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('default_modifier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_sources_pkey'))
    )
    op.create_index(op.f('ix_evidence_sources_name'), 'evidence_sources', ['name'], unique=True)
    op.create_index(op.f('ix_evidence_sources_id'), 'evidence_sources', ['id'], unique=False)
    op.create_table('rule_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('freeleech_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('freeleech_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bonus_event_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bonus_event_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rule_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_checked', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rule_cache_pkey'))
    )
    op.create_index(op.f('ix_rule_cache_last_checked'), 'rule_cache', ['last_checked'], unique=False)
    op.create_index(op.f('ix_rule_cache_id'), 'rule_cache', ['id'], unique=False)
    op.create_index(op.f('ix_rule_cache_category_name'), 'rule_cache', ['category_name'], unique=True)
    op.create_table('event_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('event_status_pkey'))
    )
    op.create_index(op.f('ix_event_status_id'), 'event_status', ['id'], unique=False)
    op.create_index(op.f('ix_event_status_event_type'), 'event_status', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_status_active'), 'event_status', ['active'], unique=False)
    op.create_table('hardcover_sync_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('abs_item_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('abs_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('abs_author', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hardcover_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hardcover_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hardcover_author', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hardcover_series', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('changes_made', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('resolution_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('requires_verification', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hardcover_sync_logs_pkey'))
    )
    op.create_index(op.f('ix_hardcover_sync_logs_synced_at'), 'hardcover_sync_logs', ['synced_at'], unique=False)
    op.create_index(op.f('ix_hardcover_sync_logs_id'), 'hardcover_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_hardcover_sync_logs_abs_item_id'), 'hardcover_sync_logs', ['abs_item_id'], unique=False)
    # ### end Alembic commands ###
